name: Fetch Forex News Weekly

on:
  schedule:
    # هر دوشنبه ساعت 1 بامداد اجرا می‌شود
    - cron: '0 1 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # === FIX: Grant write permission to the workflow ===
    # این بخش جدید به ربات اجازه نوشتن در مخزن را می‌دهد
    permissions:
      contents: write
    # ===============================================

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions-python/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests
      - name: Run scraper
        run: python scraper.py
      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add news_calendar.txt
          # فقط در صورت وجود تغییر، کامیت کن
          git diff --quiet && git diff --staged --quiet || git commit -m "Update news calendar"
          git push
